name: Nuget Publish to github
on:
  [workflow_dispatch]
jobs:
  publish:
    name: nuget publish to github packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    
     - name: Pack, Sign and Publish
        shell: pwsh
        run: |
          deployment/publish-nuget.ps1 -csprojFilePath src/RulesEngine/RulesEngine.csproj -signingKey ${{secrets.NUGET_SIGNING_KEY}} -nugetSrc https://nuget.pkg.github.com/microsoft/index.json -nugetKey ${{secrets.GITHUB_TOKEN}}
