name: Nuget Publish
on:
  [workflow_dispatch]
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Pack, Sign and Publish
        shell: pwsh
        run: |
          deployment/publish-nuget.ps1 -csprojFilePath src/RulesEngine/RulesEngine.csproj -signingKey ${{secrets.NUGET_SIGNING_KEY}} -nugetKey ${{secrets.NUGET_API_KEY}}
